version: '2'
services:
  users:
    build:
      context: ./users/service
      dockerfile: Dockerfile
    command: npm start
    depends_on:
      - users_database
    links:
      - users_database
    ports:
      - 3000
    environment:
      - DOCKER_ENV=true
      - NODE_ENV=production
      - DB_HOST=users_database
      - DB_PORT=28015
      - PORT=3000

  clients:
    build:
      context: ./clients/service
      dockerfile: Dockerfile
    command: npm start
    depends_on:
      - clients_database
    links:
      - clients_database
    ports:
      - 3000
    environment:
      - DOCKER_ENV=true
      - NODE_ENV=production
      - DB_HOST=clients_database
      - DB_PORT=28015
      - PORT=3000

  users_database:
    image: rethinkdb:latest
    ports:
      - 28015
    volumes:
      - ./users/data:/data

  clients_database:
    image: rethinkdb:latest
    ports:
      - 28015
    volumes:
      - ./clients/data:/data
