version: '2'
services:
  users:
    build:
      context: ./users/service
      dockerfile: Dockerfile
    command: npm start
    hostname: users
    depends_on:
      - users_database
      - consul
    links:
      - users_database
      - consul
    ports:
      - 3000
    environment:
      - DOCKER_ENV=true
      - NODE_ENV=production
      - DB_HOST=users_database
      - DB_PORT=28015
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - PORT=3000

  clients:
    build:
      context: ./clients/service
      dockerfile: Dockerfile
    command: npm start
    hostname: clients
    depends_on:
      - clients_database
      - consul
    links:
      - clients_database
      - consul
    ports:
      - 3000
    environment:
      - DOCKER_ENV=true
      - NODE_ENV=production
      - DB_HOST=clients_database
      - DB_PORT=28015
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - PORT=3000

  users_database:
    image: rethinkdb:latest
    ports:
      - 28015
    volumes:
      - ./users/data:/data

  clients_database:
    image: rethinkdb:latest
    ports:
      - 28015
    volumes:
      - ./clients/data:/data

  consul:
    image: gliderlabs/consul-server:latest
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap"
