version: '2'
services:
  users:
    extends:
      file: ./users-service/docker-compose.production.yml
      service: service
    restart: always
    depends_on:
      - users_database
      - consul
    links:
      - users_database
      - consul

  users_database:
    extends:
      file: ./core-services/services.yml
      service: rethinkdb_service
    volumes:
      - ./users/data:/data

  hello:
    build: ./hello-service/service
    env_file: ./hello-service/properties.env
    restart: always
    depends_on:
      - consul
    links:
      - consul

  consul:
    extends:
      file: ./core-services/services.yml
      service: consul_service

  gateway:
    extends:
      file: ./core-services/services.yml
      service: fabio_service
    links:
      - consul
