version: '2'
services:
  users:
    build:
      context: ./users-service/service
      dockerfile: Dockerfile-production
    restart: always
    ports:
      - 80
    depends_on:
      - users_database
      - consul
    links:
      - users_database
      - consul

  users_database:
    extends:
      file: ./core-services/services.yml
      service: rethinkdb_service
    volumes:
      - ./users/data:/data

  consul:
    extends:
      file: ./core-services/services.yml
      service: consul_service

  gateway:
    extends:
      file: ./core-services/services.yml
      service: fabio_service
    links:
      - consul
