version: '2'
services:
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    command: npm start
    depends_on:
      - database
    links:
      - database
    ports:
      - 80
    environment:
      - DOCKER_ENV=true
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=28015
      - CONSUL_PORT=8500
      - PORT=3000

  database:
    image: rethinkdb:latest
    ports:
      - 28015:28015
    volumes:
      - ./data:/data
