version: '2'
services:
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    command: npm start
    depends_on:
      - database
    links:
      - database
    ports:
      - 80
    environment:
      - DOCKER_ENV=true
      - NODE_ENV=production
      - PORT=80
      - DB_HOST=database
      - DB_PORT=28015
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - SERVICE_NAME=users
      - PREFIXES=/users

  database:
    image: rethinkdb:latest
    ports:
      - 28015
    volumes:
      - ./data:/data
